### ISSUE TITLE
Extra data in json

### ISSUE THREAD

**Issue by josephtocci** [mentatpsi/OSGenome#14]
When I run the import
```
# python3 SNPedia/DataCrawler.py -f /opt/genome.txt
```

I get this
```
page|5253393939393433|13372
122
122
['rs7999075', 'rs878854938', 'rs587783831', 'rs796053466', 'rs121918680', 'rs34695944', 'rs202198133', 'rs193922432', 'rs4652795', 'rs10444502']
Traceback (most recent call last):
  File "SNPedia/DataCrawler.py", line 165, in <module>
    dfCrawl = SNPCrawl(rsids=rsid, filepath=filepath)
  File "SNPedia/DataCrawler.py", line 22, in __init__
    self.importDict(filepath)
  File "SNPedia/DataCrawler.py", line 110, in importDict
    self.rsidDict = json.load(jsonfile)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 670356 (char 670355)
```

**Comment by mentatpsi** [comment]
Hi, can you check to see if your JSON file is malformed within your rsidDict.json in your data directory?

**Comment by mentatpsi** [comment]
Closing due to inactivity
