### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Callable'

### ISSUE THREAD

**Issue by sangaman** [mentatpsi/OSGenome#17]
When I try to run DataCrawler.py on my recently downloaded 23andme genome, I get this error.

```
Traceback (most recent call last):
  File "/home/danielmcnally/github/OSGenome/SNPedia/DataCrawler.py", line 168, in <module>
    dfCrawl = SNPCrawl(rsids=rsid)
  File "/home/danielmcnally/github/OSGenome/SNPedia/DataCrawler.py", line 35, in __init__
    self.initcrawl(rsids)
  File "/home/danielmcnally/github/OSGenome/SNPedia/DataCrawler.py", line 43, in initcrawl
    self.grabTable(rsid)
  File "/home/danielmcnally/github/OSGenome/SNPedia/DataCrawler.py", line 63, in grabTable
    bs = BeautifulSoup(html, "html.parser")
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/builder/_htmlparser.py", line 167, in feed
    parser.feed(markup)
  File "/usr/lib/python3.10/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/lib/python3.10/html/parser.py", line 178, in goahead
    k = self.parse_html_declaration(i)
  File "/usr/lib/python3.10/html/parser.py", line 269, in parse_html_declaration
    self.handle_decl(rawdata[i+2:gtpos])
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/builder/_htmlparser.py", line 112, in handle_decl
    self.soup.endData(Doctype)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/__init__.py", line 365, in endData
    self.object_was_parsed(o)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/__init__.py", line 370, in object_was_parsed
    previous_element = most_recent_element or self._most_recent_element
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/element.py", line 1040, in __getattr__
    return self.find(tag)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/element.py", line 1278, in find
    l = self.find_all(name, attrs, recursive, text, 1, **kwargs)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/element.py", line 1299, in find_all
    return self._find_all(name, attrs, text, limit, generator, **kwargs)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/element.py", line 528, in _find_all
    strainer = SoupStrainer(name, attrs, text, **kwargs)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/element.py", line 1596, in __init__
    self.text = self._normalize_search_value(text)
  File "/home/danielmcnally/github/OSGenome/venv/lib/python3.10/site-packages/bs4/element.py", line 1601, in _normalize_search_value
    if (isinstance(value, str) or isinstance(value, collections.Callable) or hasattr(value, 'match')
AttributeError: module 'collections' has no attribute 'Callable'
```

**Comment by mentatpsi** [comment]
Hi,

From quick analysis, you are using Python 3.10 and BeautifulSoup does not yet support it. There are some ways around it, but the quickest is to try to also install an earlier version of Python.

**Comment by sangaman** [comment]
Thanks. Which version should I try? I didn't see a python version specified.

**Comment by mentatpsi** [comment]
Hi, this bug with BeautifulSoup is new. Try 3.9 and let me know.

**Comment by mentatpsi** [comment]
I will try to create a fix for this version. But for now, an older version should do the trick. Thanks for bringing this to my attention.

**Comment by sangaman** [comment]
I tried updating the beautifulsoup version in the requirements and that did the trick, I've opened a PR.

**Comment by mentatpsi** [comment]
Hi, sorry. I don't accept PRs on this project.

**Comment by mentatpsi** [comment]
Incorporated Daniel McNally discovery into bug (outdated version of BeautifulSoup, a low risk and critical HTML processor that maps data from SNPedia). Upgraded to newest version. Thanks Daniel. Appreciate your work 🙂 

Commit:
https://github.com/mentatpsi/OSGenome/commit/cf798c12271c980bf029e84d3c2c104cf7d1acd7
